using Content.Client.UserInterface.Controls;
using Content.Shared._HoofedEar.Salvage.Bounty;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HoofedEar.Salvage.Bounty;

[GenerateTypedNameReferences]
public sealed partial class SalvageBountyMenu : FancyWindow
{
    public Action<string>? OnLabelButtonPressed;
    public Action<string>? OnSkipButtonPressed;

    public SalvageBountyMenu()
    {
        RobustXamlLoader.Load(this);

        MasterTabContainer.SetTabTitle(0, Loc.GetString("salvage-bounty-console-tab-available-label"));
        MasterTabContainer.SetTabTitle(1, Loc.GetString("salvage-bounty-console-tab-history-label"));
    }

    public void UpdateEntries(List<SalvageBountyData> bounties, List<SalvageBountyHistoryData> history, TimeSpan untilNextSkip)
    {
        BountyEntriesContainer.Children.Clear();
        foreach (var b in bounties)
        {
            var entry = new SalvageBountyEntry(b, untilNextSkip);
            entry.OnLabelButtonPressed += () => OnLabelButtonPressed?.Invoke(b.Id);
            entry.OnSkipButtonPressed += () => OnSkipButtonPressed?.Invoke(b.Id);

            BountyEntriesContainer.AddChild(entry);
        }
        BountyEntriesContainer.AddChild(new Control { MinHeight = 10 });

        BountyHistoryContainer.Children.Clear();
        if (history.Count == 0)
        {
            NoHistoryLabel.Visible = true;
        }
        else
        {
            NoHistoryLabel.Visible = false;
            for (var i = history.Count - 1; i >= 0; i--)
                BountyHistoryContainer.AddChild(new SalvageBountyHistoryEntry(history[i]));
        }
    }
}
