using Content.Client.Message;
using Content.Shared._HoofedEar.Salvage.Bounty;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._HoofedEar.Salvage.Bounty;

[GenerateTypedNameReferences]
public sealed partial class SalvageBountyHistoryEntry : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public SalvageBountyHistoryEntry(SalvageBountyHistoryData bounty)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (!_prototype.Resolve(bounty.Bounty, out var bountyPrototype))
            return;

        var items = new List<string>();
        foreach (var entry in bountyPrototype.Entries)
        {
            items.Add(Loc.GetString("salvage-bounty-console-manifest-entry",
                ("amount", entry.Amount),
                ("item", Loc.GetString(entry.Name))));
        }

        ManifestLabel.SetMarkup(Loc.GetString("salvage-bounty-console-manifest-label", ("item", string.Join(", ", items))));
        RewardLabel.SetMarkup(Loc.GetString("salvage-bounty-console-reward-label", ("reward", bountyPrototype.Reward)));
        IdLabel.SetMarkup(Loc.GetString("salvage-bounty-console-id-label", ("id", bounty.Id)));

        TimestampLabel.SetMarkup(bounty.Timestamp.ToString(@"hh\:mm\:ss"));

        if (bounty.Result == SalvageBountyHistoryData.BountyResult.Completed)
            NoticeLabel.SetMarkup(Loc.GetString("salvage-bounty-console-history-notice-completed-label"));
        else
            NoticeLabel.SetMarkup(Loc.GetString("salvage-bounty-console-history-notice-skipped-label", ("id", bounty.ActorName ?? "")));
    }
}
