using Content.Client.UserInterface.Controls;
using Content.Shared._HoofedEar.Salvage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HoofedEar.Salvage;

[GenerateTypedNameReferences]
public sealed partial class SalvageSaleMenu : FancyWindow
{
    public Action? SellRequested;
    public Action? AppraiseRequested;

    public SalvageSaleMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += _ => SellRequested?.Invoke();
        AppraiseButton.OnPressed += _ => AppraiseRequested?.Invoke();
    }

    public void UpdateState(SalvageSaleConsoleBuiState state)
    {
        RateLabel.Text = Loc.GetString("salvage-sale-menu-rate-value", ("spesos", state.SpesosPerTicket));
        SpesosLabel.Text = Loc.GetString("salvage-sale-menu-spesos-value", ("amount", state.Appraisal));
        TicketsLabel.Text = Loc.GetString("salvage-sale-menu-tickets-value", ("amount", state.Tickets));
        CountLabel.Text = state.Count.ToString();

        AppraiseButton.Disabled = !state.Enabled;
        SellButton.Disabled = !state.Enabled || state.Tickets <= 0;
    }
}
